#!/usr/bin/python3

from flask import Flask

app = Flask(__name__)

@app.route("/number/<int:n>", strict_slashes=False)
def testNum(n):
    "Prints n is a number only if n is a number"
    if isinstance(n, int):
        return f"{n} is a number"

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=5000, debug=None)
